### ISSUE TITLE
Sounding example is broken

### ISSUE THREAD

**Issue by nbald** [windycom/windy-plugins#1]
![capture d ecran de 2018-10-26 11-17-51](https://user-images.githubusercontent.com/1681443/47557402-db7e6d00-d910-11e8-93f6-0ab65a458685.png)
![capture d ecran de 2018-10-26 11-17-36](https://user-images.githubusercontent.com/1681443/47557403-dc170380-d910-11e8-9f85-e70130828a87.png)

Tested both on Chromium and Firefox

Target: index.html
Version: 16.13.1
Built: 2018-10-26, 05:58
Your browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.67 Chrome/70.0.3538.67 Safari/537.36
WebGL particles: running

Target: index.html
Version: 16.13.1
Built: 2018-10-26, 05:58
Your browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
WebGL particles: running

**Comment by ilblog** [comment]
Thx. Fixed. The name of css class that is applied to <body> tag MUST be the same as name in package.json
