### ISSUE TITLE
The sounding example is broken

### ISSUE THREAD

**Issue by vicb** [windycom/windy-plugins#2]
1) The mounting point seems to be wrong

`#map_container .leaflet-popup-pane`

`.leaflet-popup-pane` is in a sibling of `#map_container`

2) Still does not work after updating `config.s` (with the correct container).

I see an error `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` in the console, not sure if related

--

Doing some more investigation, it seems that https://github.com/windycom/windy-plugins/blob/02dba015e4ede153de6d4bc82bdee8a48b714beb/examples/07-multiple-files-plugin/soundingGraph.mjs#L591 always return -1

Forcing index = 0 make the sounding appear but without background (ie transparent)

**Comment by vicb** [comment]
Hum... seems to be working now, sorry for the noise !

**Comment by vicb** [comment]
Oops no it only sometimes works, race condition ?

**Comment by mdorda** [comment]
Thank you for reporting, we will check it.
