### ISSUE TITLE
HelloWorld not working

### ISSUE THREAD

**Issue by luigitrevisi** [windycom/windy-plugins#28]
When trying to load the Hello World example, the log console returns this:
`Unhandled Promise Rejection: TypeError: map.getCenter is not a function. (In 'map.getCenter()', 'map.getCenter' is undefined)`

**Comment by mdorda** [comment]
You are right. Thanks for bringing it up. We have launched new version of Windy with some breaking changes. Another version is on its way. After next release, we update this repository to suite it new Windy. It should not take us more than 2 weeks. Thanks for your patient.

**Comment by mdorda** [comment]
If you need to make it work quickly, just import map module as a named export:
```js
import { map } from '@windy/map';
```

**Comment by mdorda** [comment]
Fixed https://github.com/windycom/windy-plugins/commit/f1ad0f142be545064a65e55b20ab1a52f7d5b425
