### ISSUE TITLE
Coding convention

### ISSUE THREAD

**Issue by vicb** [windycom/windy-plugins#4]
It would be nice to format the code with [prettier](https://prettier.io/) or something similar.

Trying to respect existing conventions is hard and automatic formatting has always been beneficial for dev's sanity on projects I contribute too.

(And personal opinion: while I can understand that some people don't like `;` I don't think it's very good to release exemple code without them and exemples should try to stick to whatever most popular style is when there is a clear winner).

**Comment by ilblog** [comment]
Well I do not care about formatting. Whatever is good.

**Comment by ilblog** [comment]
If you want you can use prettier in this repo
