### ISSUE TITLE
onopen / onclose events 

### ISSUE THREAD

**Issue by vicb** [windycom/windy-plugins#6]
I have developed a plugin which is anchored to the context menu.

When the plugin is opened and closed explicitly (clicking on the close icon) the sequence of events is:
- `open`
- `close`

no surprise here.

However if the plugin is opened and re-opened at a different place, the sequence of event is
- `open`
- `open` -> no `close` before the second open.

This is a bit surprising and make it harder to track resources.

**I think this should be fixed ?**

I notice this because there is a `store.on("product")` called from my `onopen` which gets registered multiple times as the plugin  is re-opened at a different location.

*At first this would trigger multiple data loads when the plugin was re-opened multiple times - and this would keep going even after the plugin is closed. Until I found `store.off()`*

My suggestions for fixing this:
- better document `store.off()` ?
- wrap the `store` instance and pass it to `onopen`. The wrapped instance would automatically cancel subscriptions when the plugin is closed.

**Comment by ilblog** [comment]
This is not  a bug. It works like this and is documented in examples.

**Comment by vicb** [comment]
Call it a feature request or a rough edge if you prefer (I didn't explicitly called that a bug).

> It works like this and is documented in examples.

1) I still think docs can be improved around this - happy to contribute that,
2) Check [example 7](https://github.com/windycom/windy-plugins/blob/f8040b90f78e6752bc0ae27df91b7837c95e336f/examples/07-multiple-files-plugin/soundingGraph.mjs#L557) - the timestamp subscription is never released, meaning you will keep redrawing the sounding even after it has been closed. This is where auto unsubscribe can help - and I think we could agree that this one is a bug :)
