### ISSUE TITLE
NAM forecasts in continental US ("namConus")

### ISSUE THREAD

**Issue by vicb** [windycom/windy-plugins#7]
While both GFS and ECMWF forecasts seems to have a `origTs` field in the forecasts data that match the TS in the airData NAM doesn't.

For "namConus" `ts` and `origTs` are set to the same value.

Not sure if this is a bug or intended behavior as the doc is sparse.

It would be great to have a descriptions of all the forecast and air data (i.e. "namConus" does not provide "gh-...").

**Comment by vicb** [comment]
Also it looks like NAM has the elevation in the `header` field of the forecast while other models have it in the `header` field of the airData.

**Comment by mdorda** [comment]
Sorry for the delay. I forgot we have also this repo :-) Is it still actual?

**Comment by mdorda** [comment]
Closed due to inactivity.
